-- Create teachers table
create table public.teachers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  nip text unique,
  nama text
);

-- Enable RLS
alter table public.teachers enable row level security;

-- Add RLS policies (adjust as needed)
create policy "Teachers can view their own data" on public.teachers
  for select using (auth.uid() = user_id);

-- Optional: Allow linking via API (if using service role, this isn't strictly needed for RLS)
